[package]
name = "dnd-gm-helper"
version = "0.2.1"
edition = "2018"

[dependencies]
crossterm = "0.19.0"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
tui = { version = "0.15.0", default-features = false, features = ['crossterm'] }

